### ISSUE TITLE
Please add Composer Support

### ISSUE THREAD

**Issue by derpoho** [Nevon/swiftype-php#5]
Hey, would be great if this Lib has Composer Support!

Thanks
Marcus

**Comment by Nevon** [comment]
I'd love a PR for that. I've been out of the PHP landscape for a long time,
so I don't even have an environment set up for it.

There's lots of stuff that would be nice to have for this project, like
tests, a vagrant box for developing, CI, etc. But since I haven't been
using PHP or Swiftype for a long time, I havent gotten around to setting
any of that up. Contributions are more than welcome.
